entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
  https:
    address: :443

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

serversTransport:
  rootCAs:
    - certs/rootCA-key.pem
    - certs/rootCA.pem

providers:
  file:
    filename: "dynamic.yaml"
    watch: true
